# The name of your Flutter project.
name: jaguar_app

# A short description of what your project is about.
description: "A new Flutter project."

# Prevents accidental publishing to pub.dev, which is useful for private projects.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Versioning information for your app.
# Format: major.minor.patch+build
version: 1.0.0+1

# Specify the environment, including the Dart SDK version.
environment:
  sdk: '>=3.3.1 <4.0.0'

# Dependencies section where you specify packages your app depends on.
dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.1

  # Cupertino Icons is used for iOS-style icons in your app.
  cupertino_icons: ^1.0.6
   
  go_router: ^14.2.7

flutter_native_splash:
  color: "#ffffff" # Background color for the splash screen
  image: assets/images/article1.jpeg # Path to the splash image
  android: true
  ios: true
# Dev dependencies are only used during development and testing.
dev_dependencies:
  flutter_test:
    sdk: flutter

  # Flutter lints is a package that contains recommended lint rules.
  # These rules help you follow best practices while coding.
  flutter_lints: ^3.0.0

# This section is specific to Flutter projects.
flutter:
  # Ensures the Material Icons font is included, allowing you to use Material Icons in your app.
  uses-material-design: true

  # To add assets like images, audio, or fonts, uncomment and specify them here.
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # Example for adding custom fonts to your app.
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

# Notes:
# - The `dependencies` section is where you add packages your app needs.
# - The `dev_dependencies` section is for packages that are only needed during development, like testing libraries.
# - The `flutter` section is specific to Flutter projects, used to define assets, fonts, etc.
# - If you wish to add assets (like images), you need to uncomment the `assets` section and list the file paths.
# - To include custom fonts, the `fonts` section should be filled out accordingly.

# You can also add other sections like `flutter_icons` for custom app icons,
# `flutter_native_splash` for a custom splash screen, and more, depending on your project's needs.
